# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Download release assets
        run: |
          cp ./library/die.js ./demo/die.js

          # libv86.js
          curl -L -o ./demo/libv86.js https://github.com/xoreaxlmbdx/die-in-browser/releases/download/1.1.0/libv86.js

          # seabios.bin
          curl -L -o ./demo/seabios.bin https://github.com/xoreaxlmbdx/die-in-browser/releases/download/1.1.0/seabios.bin

          # v86.wasm
          curl -L -o ./demo/v86.wasm https://github.com/xoreaxlmbdx/die-in-browser/releases/download/1.1.0/v86.wasm

          # v86state.zst
          curl -L -o ./demo/v86state.zst https://github.com/xoreaxlmbdx/die-in-browser/releases/download/1.1.0/v86state.zst

          # vgabios.bin
          curl -L -o ./demo/vgabios.bin https://github.com/xoreaxlmbdx/die-in-browser/releases/download/1.1.0/vgabios.bin
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: './demo'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
